#!./.iris-sklearn/bin/python
import os
import json

import docker
import fire

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss

from fedn.utils.helpers.helpers import get_helper, save_metadata, save_metrics

HELPER_MODULE = 'numpyhelper'
helper = get_helper(HELPER_MODULE)

NUM_CLASSES = 10


def _get_data_path():
    """ For test automation using docker-compose. """
    # Figure out FEDn client number from container name
    client = docker.from_env()
    container = client.containers.get(os.environ['HOSTNAME'])
    number = container.name[-1]

    # Return data path
    return f"/var/data/clients/{number}/iris.json"


def compile_model():
    """ Compile the sklearn model.

    :return: The compiled model.
    :rtype: sklearn.linear_model._logistic.LogisticRegression
    """

    return LogisticRegression(max_iter=1000)


def load_data(data_path, is_train=True):
    """ Load data from disk.

    :param data_path: Path to data file.
    :type data_path: str
    :param is_train: Whether to load training or test data.
    :type is_train: bool
    :return: Tuple of data and labels.
    :rtype: tuple
    """

    if data_path is None:
        with open(_get_data_path(), 'r') as json_file:
            data = json.load(json_file)
    else:
        with open(data_path, 'r') as json_file:
            data = json.load(json_file)

    if is_train:
        X = data['x_train']
        y = data['y_train']
    else:
        X = data['x_test']
        y = data['y_test']

    # Normalize - Do we normalize?

    return X, y


def save_parameters(model, out_path):
    """ Save model paramters to file.

    :param model: The model to serialize.
    :type model: sklearn.linear_model._logistic.LogisticRegression
    :param out_path: The path to save to.
    :type out_path: str
    """
    parameters_np = np.concatenate((model.coef_, model.intercept_.reshape(-1, 1)), axis=1)

    helper.save(parameters_np, out_path)


def load_parameters(model_path):
    """ Load model parameters from file and populate model.

    param model_path: The path to load from.
    :type model_path: str
    :return: The loaded model.
    :rtype: torch.nn.Module
    """
    model = compile_model()
    model.fit([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [0, 1, 2])
    parameters_np = np.array(helper.load(model_path))

    # print(np.array(parameters_np))

    model.coef_ = parameters_np[:, 0:4]
    model.intercept_ = parameters_np[:, -1]

    return model


def init_seed(out_path='seed.npz'):
    """ Initialize seed model and save it to file.

    :param out_path: The path to save the seed model to.
    :type out_path: str
    """
    # Init and save
    model = compile_model()
    model.fit([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [0, 1, 2])

    save_parameters(model, out_path)


def train(in_model_path, out_model_path, data_path=None, malicious=False, attack=None, batch_size=32):
    """ Complete a model update.

    Load model paramters from in_model_path (managed by the FEDn client),
    perform a model update, and write updated paramters
    to out_model_path (picked up by the FEDn client).

    :param in_model_path: The path to the input model.
    :type in_model_path: str
    :param out_model_path: The path to save the output model to.
    :type out_model_path: str
    :param data_path: The path to the data file.
    :type data_path: str
    :param batch_size: The batch size to use.
    :type batch_size: int
    :param epochs: The number of epochs to train.
    :type epochs: int
    :param lr: The learning rate to use.
    :type lr: float
    """
    # Load data
    x_train, y_train = load_data(data_path)
    x_train = pd.DataFrame(x_train)
    y_train = pd.DataFrame(y_train)

    # Load parmeters and initialize model
    model = load_parameters(in_model_path)

    # Train
    model.fit(x_train, y_train.values.ravel())

    # Metadata needed for aggregation server side
    metadata = {
        # num_examples are mandatory
        'num_examples': len(x_train),
        'batch_size': batch_size
    }

    # Save JSON metadata file (mandatory)
    save_metadata(metadata, out_model_path)

    # Save model update (mandatory)
    save_parameters(model, out_model_path)


def validate(in_model_path, out_json_path, data_path=None):
    """ Validate model.

    :param in_model_path: The path to the input model.
    :type in_model_path: str
    :param out_json_path: The path to save the output JSON to.
    :type out_json_path: str
    :param data_path: The path to the data file.
    :type data_path: str
    """
    # Load data
    x_train, y_train = load_data(data_path)
    x_train = pd.DataFrame(x_train)
    y_train = pd.DataFrame(y_train)
    x_test, y_test = load_data(data_path, is_train=False)
    x_test = pd.DataFrame(x_test)
    y_test = pd.DataFrame(y_test)

    # Load model
    model = load_parameters(in_model_path)

   # JSON schema
    report = {
        "training_loss": log_loss(y_train, model.predict_proba(x_train)),
        "training_accuracy": accuracy_score(y_train, model.predict(x_train)),
        "test_loss": log_loss(y_test, model.predict_proba(x_test)),
        "test_accuracy": accuracy_score(y_test, model.predict(x_test)),
    }

    # Save JSON
    save_metrics(report, out_json_path)


if __name__ == '__main__':
    fire.Fire({
        'init_seed': init_seed,
        'train': train,
        'validate': validate,
    })
